// v5.3.1190
(function(l,g,w,D,B,x,u,y,T,N,ga,t,E,z,C,F,v,U,ha,V){function W(a,b,d){if(!a)for(a in r)return r[a];var c=new ia(a);d&&c.ga();return r[b||a]=c}function X(a){for(var b in r)r[U](b)&&a(r[b])}function sa(a,b){return function(){a.call(b)}}function O(a){return"object"==typeof a}function A(a,b,d,c){var e;(e=a.addEventListener)?e.call(a,b,d,0):a.attachEvent(c||"on"+b,d)}function s(a,b){return function(){a(b)}}function Y(a){var b=[],d;for(d in a)a[U](d)&&a[d]!==m&&b.push(T(d)+"="+T(a[d]));return b.join("&")}
function G(a,b,d,c){if(a&&a.call)a();else if(/^GSN-.*-.$/.test(a))b!==""+b&&(d=b,b=0),W(a,b,d||d===m);else if(/^_/.test(a))P[a]&&P[a](b,d),delete P[a];else{a=a[t](".");var e;1<a[z]&&(e=a.shift());a=a[0];var h={usecookies:1,anonymizeip:2,visitorname:3,username:3,statuscode:5,cookiedomain:6,trackparams:7,trackhash:8,tracklocal:9,referrer:10,visitorid:11,visitor:4},f=function(a,b,d){e?r[e].A(a,b,d):X(function(c){c.A(a,b,d)})};if(/transaction$/i.test(a))return ta(e,b,d,c);if("get"==a)return d=h[(b+"")[F]()]||
b,e?c=r[e].c(d):X(function(a){c=a.c(d)}),c;"set"==a?(a=(b+"")[t]("."),b=a.shift(),f(h[b[F]()]||b,d,a.join("."))):"track"==a?Q(Z,e,b,d,c):"event"==a?Q($,e,b,d,c):"cancel"==a?Q(function(){this.C()},e):"noCookies"==a?f(1,0):"anonymizeIP"==a?f(2,1):"tag"==a?f(3,b):"load"==a&&b&&b()}}function I(a,b){return((a>>1)+(b>>1)<<1)+(a&1)+(b&1)}function ja(a,b){function d(a){return"expires="+(new x(a)).toGMTString()+";"}var c="path=/;",e=a.c(6);e&&(c+="domain="+e+";");return{J:function(e,f){a.c(1,1)&&(g.cookie=
e+"="+f+";"+d(+new x+(b?6E10:6E4))+c)},G:function(b){if(a.c(1,1))return(g.cookie.match("(^|;)\\s*"+b+"=([^;]*)")||[])[2]||m},Q:function(a){g.cookie=a+"=;"+d(0)+c}}}function Q(a,b,d,c,e){b?a.call(r[b],d,c,e):X(function(b){a.call(b,d,c,e)})}function ia(a){var b=this;b.f=a;b.ka=0;var d=[];b.A=function(a,c,f){if(4===a){a=b.n=b.n||{};var k={};if(!f&&!O(c))throw Error("Not an object");f?a[f]=k[f]=c:k=b.n=c;b.c(11)&&ka(b,k);d[4]=b.n}else d[a]=c};b.c=function(a,b){return a in d?d[a]:b};var c;b.ga=function(){c=
u(sa(Z,b),200)};b.C=function(){y(b.j);y(c)}}function Z(a,b,d){a&&a.call&&(d=a,a=m);b&&b.call&&(d=b,b=m);var c=this,e=ua(c,a,b),h=va(c);b=wa(c,!h.H,a!==m);var f=xa(),k=aa(),H=c.c(5);y(c.j);c.m=0;c.h=0;ba(c);!c.c(9)&&e.V||e.U||w&&"preview"==w.loadPurpose||f.g.B&&f.g.r&&10>f.g.B&&10>f.g.r||(c.t=k.l,c.s=k.k,e={a:c.f,cs:f.O,cd:f.N,fl:f.T,je:f.W,la:f.X,sw:f.g.B,sh:f.g.r,dp:f.S,pu:e.ha,pt:e.fa,ri:h.H,ru:h.da,ui:b.b,re:b.ea,vi:b.ia,pv:b.ca,lv:b.Y,vw:k.M,vh:k.L,dw:k.F,dh:k.D,st:k.l,sl:k.k,tv:N,un:c.c(3),pp:b.ba,
cp:b.P,ec:H,aip:c.c(2)?1:m,tz:f.Z},c.A(11,b.b),q&&(c.uid=b.b,e.bc=1),J?(e.o_si=J,e.o_vi=ca,e.o_ci=da):c.I=1,c.aa=0,R("pv",e,function(a){a!==m&&(c.b=a,y(c.j),c.j=u(s(S,c),5E3),d&&d())},5),c.b===m?(u(s(ya,c),500),A(l,"beforeunload",s(za,c))):a!==m&&(c.b=m))}function $(a,b,d){b&&b.call&&(d=b,b=m);if(b===""+b||b===+b)b={caption:b};b||(b={});var c={},e;for(e in b)b[U](e)&&(c[e]=b[e]);c.gs_evt_name=a;S(this,"event",c,d)}function S(a,b,d,c){if(a.b!==m){if(!d){var e=aa();d={vw:e.M,vh:e.L,dw:e.F,dh:e.D,st:e.l,
sl:e.k,mst:a.t,msl:a.s}}d.a=a.f;d.u=a.c(11);d.i=a.b;d.e=b;d.tv=N;d.et=Aa(a);q&&(d.bc=1);a.I&&J&&(a.I=0,d.o_si=J,d.o_vi=ca,d.o_ci=da);R("ping",d,function(){c&&c();y(a.j);a.j=u(s(S,a),[7E3,12E3][a.aa++]||17500+5E3*B.random())},5)}else u(function(){S(a,b,d,c)},5E3)}function ka(a,b){a.b===m&&u(function(){ka(a,b)},5E3);b[C]&&(b[C]=la(b[C][E](/^\s+|\s+$/g,"")[F]()));R("prop",{a:a.f,u:a.c(11),p:Y(b),tv:N},s,5)}function ma(){var a=l.olark;a&&a("api.boot.onIdentityReady",function(a,d,c){J=a;ca=d;da=c})}function R(a,
b,d,c){var e=u(function(){f&&f();ea=(ea+1)%fa[z];b.et&&(b.et=0);b.rt=1;--c&&R(a,b,d,c)},1E4);b.cb=Ba(function(a){d(a);f&&f();y(e)});var h=a+"?"+Y(b),f;na?na.ja(h):f=Ca(h)}function Ca(a){var b=g[ha]("head")[0],d=g[ga]("script");d.src=(Da?"https":"http")+"://"+fa[ea]+a;b.appendChild(d);return function(){d&&b.removeChild(d);d=null}}function Ba(a){var b="_"+Ea++;P[b]=a;return b}function K(a){function b(){var a=e[v];a&&(e[v]=a[t](d)[0])}var d=":_GS_:",c;if(K.K)return K.K;var e=l.top;K.K=c={R:function(){b();
e[v]=(e[v]||"")+d+[a,c.b,c.w]}};try{var h=e[v]||"";if(-1!=h[V](d)){var f=h[t](d)[1][t](",");f[0]==a&&(c.b=f[1]||"",c.w=f[2]||"")}b()}catch(k){e={}}return c}function ua(a,b,d){var c=g[ga]("a");c.href=b||l.location.href;b=c.href;a.c(7,1)||(b=b[E](/\?[^#]*/,""));a.c(8)||(b=b[E](/#.*$/,""));return{ha:b,fa:d!==m?d:g.title,V:/^file:/.test(b)||/\/\/localhost[\/:]/.test(b+"/"),U:/fb_xd_(bust|fragment)/.test(b)}}function xa(){var a,b,d,c,e,h,f=0,k=0;D&&(f=D.width,k=D.height);e=(e=l.orientation)&&(e+360)%180;
return{g:{B:e?k:f,r:e?f:k},N:D&&D.colorDepth||"-",X:(w.language||w.browserLanguage||"-")[F](),W:+w.javaEnabled(),O:g.characterSet||g.charSet||"-",T:function(f,k){if(w&&(a=w.plugins)&&0<(b=a[z]))for(e=0;e<b;e++){if(-1<(c=a[e])[v][V](d=f+" "+k))return h=c.description[t](d+" "),h[1]}else if(h=l.ActiveXObject){try{if(c=(new h((d=f+k+".")+f+k)).GetVariable("$version"))return c=c[t](" ")[1][t](","),c[0]+"."+c[1]+" r"+c[2]}catch(g){}for(e=13;--e;)try{if(c=(c=new h(d+d+e))&&1)return e+".0"}catch(m){}}return"-"}("Shockwave",
"Flash"),S:l.devicePixelRatio||1,Z:(new x).getTimezoneOffset()}}function aa(){function a(a){return l["inner"+a]||c&&c[e="client"+a]||d&&d[e]}function b(a){return B.max(d[e="scroll"+a]||0,c[e]||0,d[e="offset"+a],c[e],d[e="client"+a],c[e])}var d=g.body,c=g.documentElement,e;return{M:a("Width"),L:a("Height"),F:b("Width"),D:b("Height"),k:l.pageXOffset||c&&c.scrollLeft||0,l:l.pageYOffset||c&&c.scrollTop||0}}function ba(a){y(a.$);a.$=u(s(oa,a),15E3);a.h||(a.h=1,a.o=+new x)}function oa(a){a.h&&(a.h=0,a.m=
(a.m||0)+ +new x-a.o)}function Aa(a){var b=a.m,d=+new x;a.h&&(b+=d-a.o,a.o=d);a.m=0;return b}function Fa(a){ba(a);var b=aa();b.l>a.t&&(a.t=b.l);b.k>a.s&&(a.s=b.k)}function ya(a){var b=s(ba,a);A(g,"mousemove",b);A(g,"keydown",b);A(l,"scroll",s(Fa,a));A(g,"focus",b,"focusin");A(g,"blur",s(oa,a),"focusout")}function va(a){a=a.c(10,g.referrer);var b;!a||/^(chrome|about|file):/.test(a)||/^\[.*\]$/.test(a)?a="-":b=a[E](/^.*?\/\//,"")[V](g.domain);return{H:+(0<=b&&8>=b),da:a}}function za(a){if(a.b!==m){var b=
ja(a);a.c(1,1)?b.J("gs_p_"+a.f,a.b):(b=K(a.f),b.w=a.b,b.R())}}function wa(a,b,d){var c=ja(a,1),e=K(a.f),h=(c.G("gs_u_"+a.f)||e.b||"")[t](":"),f=c.G("gs_p_"+a.f)||e.w,k=1,H,g,l=h[0]||(k=0,0|2147483647*B.random());b=+(h[1]||2019)+548*!!b;var n=+(h[2]||4621)+379,h=(h[3]||0)/1E3;c.J("gs_u_"+a.f,e.b=[l,b,n,+new x].join(":"));f!==m&&(H=f,c.Q("gs_p_"+a.f));d&&(H=a.b);(a=a.n)&&"object"==typeof a&&(a[C]&&(a[C]=la(a[C][E](/^\s+|\s+$/g,"")[F]())),g=Y(a));return{b:+l,ia:(b-2019)/548,ca:(n-4621)/379,Y:~~h,ea:k,
ba:H,P:g}}function ta(a,b,d,c){function e(a,b){b=b||(O(a)?a:{});O(a)||(b[v]=a);if(!b[v])throw Error("No Name");k.push(b);return g}function h(a){for(var b=0;b<a[z];)e(a[b++]);return g}function f(){Q($,a,"_transaction",{d:JSON.stringify({id:b,i:k,d:d})})}!d&&O(b)&&(d=b,b=d.id);if(!b)throw Error("No ID");var k=[];c&&h(c);d&&d.track&&f();var g={id:b,addItem:e,addItems:h,track:f};return g}var m,L,n=l._gs||(L=1,function(){pa.push(arguments)}),pa=n.q=n.q||[];if(!n.v){var r={},q=l.GoSquared;if(q){var p,M;
for(p in q)M=q[p],"acct"==p?(W(M,"_default",1),n(function(){function a(a){b[a.shift()].apply(b,a)}var b=q.DefaultTracker=r._default;if(p=q.q)for(;M=p.shift();)a(M);q.q={push:a};(p=q.load)&&p(b)})):"load"!=p&&"q"!=p&&n("set",p,M);p=ia.prototype;p.TrackView=Z;p.TrackEvent=$;p.Cancel=function(){this.C()};q.Tracker=W;q.Cancel=s(G,"cancel")}for(var qa=[],n=0;64>n;)qa[n]=0|4294967296*B.abs(B.sin(++n));var la=function(a){var b,d,c,e,h=[];a=unescape(T(a));for(var f=a[z],k=[b=1732584193,d=-271733879,~b,~d],
g=0;g<=f;)h[g>>2]|=(a.charCodeAt(g)||128)<<8*(g++%4);h[a=16*(f+8>>6)+14]=8*f;for(g=0;g<a;g+=16){f=k;for(e=0;64>e;)f=[c=f[3],I(b=f[1],(c=I(I(f[0],[b&(d=f[2])|~b&c,c&b|~c&d,b^d^c,d^(b|~c)][f=e>>4]),I(qa[e],h[[e,5*e+1,3*e+5,7*e][f]%16+g])))<<(f=[7,12,17,22,5,9,14,20,4,11,16,23,6,10,15,21][4*f+e++%4])|c>>>32-f),b,d];for(e=4;e;)k[--e]=I(k[e],f[e])}for(a="";32>e;)a+=(k[e>>3]>>4*(1^e++&7)&15).toString(16);return a},J,ca,da,fa=["data.gosquared.com/","data2.gosquared.com/"],ea=0|B.random()*fa[z],Da=/^https:/.test(l.location),
na,P={},Ea=0;l._gs=G;for(G.v=N;n=pa.shift();)G.apply({},n);if(L){L=g[ha]("script");for(var n=L[z],ra;n--;)(ra=L[n].getAttribute("data-gs"))&&G(ra)}ma();A(l,"load",ma)}})(window,document,navigator||{},screen,Math,Date,setTimeout,clearTimeout,encodeURIComponent,"5.3.1190","createElement","split","replace","length","gravatar","toLowerCase","name","hasOwnProperty","getElementsByTagName","indexOf");
